---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: vpn1
  namespace: wireguard
spec:
  mtu: "1380"
  serviceType: NodePort
  enableIpForwardOnPodInit: true
  port: 31820
  address: 109.245.66.242
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: vpn1-artem1
  namespace: wireguard
spec:
  wireguardRef: vpn1
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: vpn1-artem2
  namespace: wireguard
spec:
  wireguardRef: vpn1
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: vpn1-mari1
  namespace: wireguard
spec:
  wireguardRef: vpn1
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: vpn1-mari2
  namespace: wireguard
spec:
  wireguardRef: vpn1
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: vpn1-igor1
  namespace: wireguard
spec:
  wireguardRef: vpn1
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: vpn1-igor2
  namespace: wireguard
spec:
  wireguardRef: vpn1
---
